# Generated by Django 5.2.7 on 2025-11-08 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_customuser_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='availability_status',
            field=models.BooleanField(default=False),
        ),
    ]
