# Generated by Django 5.2.7 on 2025-11-08 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_customuser_availability_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='are_you_donor',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
