# Generated by Django 5.2.7 on 2026-01-09 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_customuser_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='blood_group',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='are_you_donor',
            field=models.BooleanField(default=True),
        ),
    ]
