# Generated by Django 5.2.7 on 2026-01-09 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0003_alter_donationhistory_receiver'),
        ('user', '0011_remove_customuser_blood_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='blood_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='blood.bloodgroup'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='age',
            field=models.IntegerField(default=22),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='are_you_donor',
            field=models.BooleanField(),
        ),
    ]
